### ISSUE TITLE
This git repo = 913356

### ISSUE THREAD

**Issue by fransvanberckel** [packethost/packet-images#36]
What wrong with this git repo?

$ du -a . | sort -n -r
913356	.
913280	./.git
912960	./.git/objects
912952	./.git/objects/pack
910428	./.git/objects/pack/pack-80014695f3aa219a38917b1754141a2a702893b3.pack
2520	./.git/objects/pack/pack-80014695f3aa219a38917b1754141a2a702893b3.idx
60	./tools
8	./README.md

**Comment by displague** [comment]
Hi, @fransvanberckel. This is a git-lfs project: https://docs.github.com/en/github/managing-large-files/configuring-git-large-file-storage

You'll need to install the git lfs plugin (if you can't already use `git lfs`):
https://docs.github.com/articles/installing-git-large-file-storage/

See the Github docs for more on the usage of Git LFS within Github projects.
